---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-test-volume
  labels:
    app: hw6-ecolley3-test-redis
    env: test
    username: ecolley3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi