---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecolley3-test-flask-deployment
  labels:
    username: ecolley3
    env: test
    app: ecolley3-test-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecolley3-test-flask
  template:
    metadata:
      labels:
        app: ecolley3-test-flask
    spec:
      containers:
        - name: flask-latest
          image: ecolley3/homework06_flask:latest